### ISSUE TITLE
Article heeft geen heading

### ISSUE THREAD

**Issue by Annevd** [wingsvn/connect-your-tribe-profile-card#6]
![image](https://github.com/wingsvn/connect-your-tribe-profile-card/assets/144004647/b1b4721a-fb2a-4af3-a100-4ed7f24cf8b3)
https://github.com/wingsvn/connect-your-tribe-profile-card/blob/477153f996ec525916a717db05e8a6a896e9f538/views/index.ejs#L18-L20

Hier gebruik je een article element zonder heading. 

Omdat articles een heading zoals h1-h6 verwachten kan je kijken of dat article echt nodig is of beter door een ander element kan worden vervangen of volledig weg te laten.

**Comment by wingsvn** [comment]
Ik neem dit mee in mijn volgende project.
