### ISSUE TITLE
color contrast button hover

### ISSUE THREAD

**Issue by lisagjh** [wingsvn/connect-your-tribe-profile-card#8]
op de contact button zit een hover waarbij het kleur contrast erg laag is, 1.5:1

<img width="600" alt="Scherm­afbeelding 2024-02-09 om 11 16 27" src="https://github.com/wingsvn/connect-your-tribe-profile-card/assets/131701505/0f7f6c18-1dc9-4441-9a01-a939c9f8ee0b">

probeer de tekstkleur zwart te maken bij hover of voor een andere achtergrond kleur te kiezen.

**Comment by wingsvn** [comment]
Dankjewel, ik zal je feedback meenemen naar mijn volgende project
