### ISSUE TITLE
Profiel foto proberen uit de api te halen?

### ISSUE THREAD

**Issue by Davidvboxt** [wingsvn/connect-your-tribe-profile-card#9]
https://github.com/wingsvn/connect-your-tribe-profile-card/blob/477153f996ec525916a717db05e8a6a896e9f538/views/index.ejs#L6C30-L6C41

Probeer misschien je profielfoto ook uit de api te halen.

**Comment by wingsvn** [comment]
Dankjewel, ik zal dit meenemen in mijn volgende project.
